git:
  depth: 1
sudo: false
language: node_js
node_js:
 - 'node'
 - '8'
 - '7'
 - '6'

notifications:
  email: false

cache:
  directories:
    - node_modules
    - $HOME/.npm

before_install:
  - if [[ `node -v` == v6* ]]; then npm i -g npm@latest-4; fi
  - if [[ `node -v` == v8* ]]; then npm i -g npm@latest-5; fi
  - npm i

script:
  - npm run build
  - npm run test

env:
  global:
    - HUBOT_PORT=8080

matrix:
  fast_finish: true